DECLARE @values NVARCHAR(MAX) = '';
DECLARE @i INT = 1;

WHILE @i <= 30
BEGIN
    SET @values += CAST(@i AS NVARCHAR) + CASE WHEN @i < 30 THEN ', ' ELSE '' END;
    SET @i += 1;
END

DECLARE @sql NVARCHAR(MAX) = '
CREATE PARTITION FUNCTION pf_funcn (INT)
AS RANGE LEFT FOR VALUES (' + @values + ');';

PRINT @sql;

CREATE PARTITION SCHEME ps_example
AS PARTITION pf_funcn
ALL TO ([PRIMARY]);